### ISSUE TITLE
plugin fails on second load, searching for missing cache file

### ISSUE THREAD

**Issue by paultopia** [whitequark/rainbowth#11]
Hi there,

So I can get rainbowth to function on first install, but when I close ST3 and reopen, it fails with the following traceback:

> Traceback (most recent call last):
>   File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 333, in on_activated_async
>     callback.on_activated_async(v)
>   File "rainbowth in /Users/pauliglot/Library/Application Support/Sublime Text 3/Installed Packages/Rainbowth.sublime-package", line 182, in on_activated_async
>   File "rainbowth in /Users/pauliglot/Library/Application Support/Sublime Text 3/Installed Packages/Rainbowth.sublime-package", line 168, in update_color_scheme
>   File "rainbowth in /Users/pauliglot/Library/Application Support/Sublime Text 3/Installed Packages/Rainbowth.sublime-package", line 69, in write_cache
> FileNotFoundError: [Errno 2] No such file or directory: 'Rainbowth/Rainbowth.cache'

It looks like installing via package control just puts some kinda binary into Installed Packages, not into the Packages directory, and then it's trying to find a cache file somewhere in the Packages directory...?

**Comment by paultopia** [comment]
same thing happens on manual install via the Packages directory

**Comment by paultopia** [comment]
just out of curiosity, I tried creating an empty Rainbowth.cache file, and now it just silently fails

**Comment by paultopia** [comment]
ok, a bit more investigation here: after poking through the code a bit, it's looking in the caches directory, not the plugin directory (sorry), but it also seems to not be aware of the existence of files that clearly exist.  Once again, got it working once, verified the cache exists, then failed on the second attempt.  The caches file seems to exist now, but Rainbowth still silently fails.  (see screenshots)

<img width="1280" alt="screenshot 2016-03-14 14 10 20" src="https://cloud.githubusercontent.com/assets/11756255/13756592/9a904ac0-e9ee-11e5-9ade-a7b50d34b47b.png">
<img width="1280" alt="screenshot 2016-03-14 13 41 57" src="https://cloud.githubusercontent.com/assets/11756255/13756594/9af0cbc0-e9ee-11e5-87f9-c8c1e16ac42f.png">

**Comment by whitequark** [comment]
Could it be that the current directory of the embedded Python differs from what it should be? (Maybe some other plugin.) It seems to use a relative path, which it probably shouldn't.

**Comment by whitequark** [comment]
Actually, your error makes no sense. It refers to `Rainbowth/Rainbowth.cache` but I specifically use the absolute path (see https://github.com/whitequark/rainbowth/blob/master/rainbowth.py#L52) to prevent this class of problem. What does `sublime.cache_path()` return?

**Comment by paultopia** [comment]
very weird indeed. `sublime.cache_path()`  /Users/pauliglot/Library/Application Support/Sublime Text 3/Cache (which is the right user).  `sys.executable` just returns python3, which I assume refers to the interpreter bundled with ST3 (I think my default system interpreter is 2.7 anyway).

So here's something more interesting and bizarre that I just tried.

I closed ST3 and reopened it, no rainbow parens but no errors in the console. 

Then I closed the .clj file I was working on, and reopened it.  It threw the same error message, but _the rainbow parens appeared_.  Making it even more confusing, a second error showed up as well.  Both full traces: 

> Traceback (most recent call last):
>   File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 231, in run_callback
>     expr()
>   File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 270, in <lambda>
>     run_callback('on_close', callback, lambda: callback.on_close(v))
>   File "/Users/pauliglot/Library/Application Support/Sublime Text 3/Packages/Rainbowth/rainbowth.py", line 208, in on_close
>     del self.view_infos[view.id()]
> KeyError: 15
> Traceback (most recent call last):
>   File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 333, in on_activated_async
>     callback.on_activated_async(v)
>   File "/Users/pauliglot/Library/Application Support/Sublime Text 3/Packages/Rainbowth/rainbowth.py", line 182, in on_activated_async
>     colors = self.update_color_scheme(view)
>   File "/Users/pauliglot/Library/Application Support/Sublime Text 3/Packages/Rainbowth/rainbowth.py", line 168, in update_color_scheme
>     self.write_cache()
>   File "/Users/pauliglot/Library/Application Support/Sublime Text 3/Packages/Rainbowth/rainbowth.py", line 69, in write_cache
>     with open(self.cache_file_path, 'w') as cache_file:
> FileNotFoundError: [Errno 2] No such file or directory: 'Rainbowth/Rainbowth.cache'

This is really quite mysterious.  Tempted to just wrap the whole thing in a try/except: pass block and see what happens.

**Comment by whitequark** [comment]
Ah yes. I figured it out. During startup, `sublime.cache_path()` returns `""` for whatever inane reason. I might be using the API not quite correctly... hrm.

**Comment by paultopia** [comment]
Hah, it would help if the lovely folks behind ST3 actually bothered to write documentation.  By the way, thank you so much for writing this thing---newbie lispers like me rejoice at not having to switch to emacs :-)

**Comment by whitequark** [comment]
I think that's one person. Anyhow, calling it during startup is playing fast and loose enough that I should've known better myself.
