### ISSUE TITLE
Doesn't rainbow :(

### ISSUE THREAD

**Issue by barneywilliams** [whitequark/rainbowth#12]
I have been looking for a rainbow parens plugin for some time now for Sublime, and just ran across this one. But it isn't working for me and others... I installed from Package Control into ST3 (build 3109) and am in OSX El Capitan.

I would LOVE to get this working. Hopefully there is some setup I am missing or something easy to fix ;)

**Comment by barneywilliams** [comment]
So it looks like the issue is that you are expecting the color schemes to be extracted into the user's Packages folder, which isn't the case anymore per Sublime 3. I wasn't able to find the extracted packages anywhere on my file system, so I don't know where you should look.

I believe that Sublime can still use manually extracted packages, so I guess this would work with manually installed themes?

**Comment by barneywilliams** [comment]
OK. Yeah, I confirmed that if I copy the `Color Scheme - Default.sublime-package` file in `/Applications/Sublime Text.app/Contents/MacOS/Packages` to a temp location.

I can then extract it using `unzip`. I then pull the desired *.tmTheme file out and place it in `~/Library/Application Support/Sublime Text 3/Packages`.

I also renamed the theme file, and the theme name tag in the file, to differentiate.

Finally, I can switch to the new copy of the theme in Sublime, and I get rainbows!

**Comment by whitequark** [comment]
Yep, this is mentioned [in README](https://github.com/whitequark/rainbowth#installation).

**Comment by no-longer-on-githu-b** [comment]
I tried everything but I just couldn't get it to work. Could you provide step-by-step instructions on how to installed Rainbowth?

**Comment by whitequark** [comment]
What do you see in the ST console?

**Comment by no-longer-on-githu-b** [comment]
I unzipped `Railscast Extended.sublime-package` and copied the tmTheme file to `~/.config/sublime-text-3/Packages` (I also tried `~/.config/sublime-text-3/Packages/User`). There is no output in the console. I also tried to reinstall Rainbowth.

**Comment by whitequark** [comment]
The `.tmTheme` should be in `~/.config/sublime-text-3/Packages/Railscast Extended/`

**Comment by ItamarShDev** [comment]
I too cant get ti to work.
took BlackRain scheme from ``~/.config/sublime-text-3/Installed Packages``
uzipped it
modified filename and theme name to `BlackRainBow`
saved the tmTheme file to ``~/.config/sublime-text-3/BlackRainBow/``
change scheme in sublime to `BlackRainBow`

no rainbow

what am i missing?

**Comment by ItamarShDev** [comment]
```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 530, in on_activated_async
    callback.on_activated_async(v)
  File "/home/itamar/.config/sublime-text-3/Packages/Rainbowth/rainbowth.py", line 190, in on_activated_async
    colors = self.update_color_scheme(view)
  File "/home/itamar/.config/sublime-text-3/Packages/Rainbowth/rainbowth.py", line 160, in update_color_scheme
    lineHighlight = self.get_setting(scheme_xml, 'lineHighlight')
  File "/home/itamar/.config/sublime-text-3/Packages/Rainbowth/rainbowth.py", line 109, in get_setting
    settings, flags=re.DOTALL).group(1)
```

**Comment by hgsadhrakiya** [comment]
Can anyone guide me with the steps to setup this in windows 10?

Thank you!
