### ISSUE TITLE
Would be super cool to be able to disable the line-highlight background on current line

### ISSUE THREAD

**Issue by emilyst** [whitequark/rainbowth#21]
Not sure if this is possible, but the different background color that brackets/parentheses get on the current line is something I'd like to disable. It looks crude on a high-definition display and is distracting to me besides.

![screen shot 2017-06-14 at 11 09 42](https://user-images.githubusercontent.com/528994/27147586-2f325db0-50f2-11e7-8b40-7c95fc3f6307.png)

Thanks in advance.

**Comment by whitequark** [comment]
I think this is basically the same as https://github.com/whitequark/rainbowth/issues/8. Now that ST has an active maintainer again, please ask them for assistance. The closest thing to the root cause that I could determine is as follows:

> The problem is that if I leave the background transparent, Sublime draws the border around the letter with the foreground color, instead of changing the color of the letter. My fix to that consisted of extracting the default background color (and for highlighted line too), and setting it explicitly. And some letters, notably % or italic m, are intersecting with the background that it draws.

Unfortunately I do not have time to handle this myself.

**Comment by emilyst** [comment]
Thanks for the infos. I'll close if you can't work on it.

**Comment by emilyst** [comment]
Oh, just to clarify, in case someone else stumbles over this: my beef isn't that the background for the brackets clips the adjacent letters. Just that the background happens to be highlighted on whatever line the cursor happens to be on. I had had the impression this was something Rainbowth was doing on purpose, but if it's inherent Sublime Text behavior, it's just as well. I just am not sure how to report it.
