### ISSUE TITLE
I can't get it to work 

### ISSUE THREAD

**Issue by eniac314** [whitequark/rainbowth#23]
I am using ubuntu and sublime text 3 (build 3143)
I installed the plugin via package control and pasted Rainbowth.sublime-settings into .config/sublime-text-3/Packages/User but nothing seems to happen. 

Did I do something wrong?

**Comment by KevinSheedy** [comment]
I also can't get it to work on Windows or Mac

Windows 7 Enterprise SP1
Sublime 3.0 Build 3143

macOS High Sierra 10.13.2
Sublime 3.0, Build 3143

**Comment by ItamarShDev** [comment]
![image](https://user-images.githubusercontent.com/953371/34384516-3c6288de-eb25-11e7-843e-6102e63a4b7d.png)

**Comment by ItamarShDev** [comment]
Do you have any error in sublime console?

**Comment by KevinSheedy** [comment]
@ItamarShDev I can't see any error, just:
`reloading plugin Rainbowth.rainbowth`

**Comment by ItamarShDev** [comment]
Did you export your color scheme to `User/<SchemeName> `?

**Comment by KevinSheedy** [comment]
Ok, I see this line in README.md:

`The color scheme must be unpacked in the user's Packages folder and writable for Rainbowth to be able to automatically insert its palette.`

However, I can't find any info about what this means or how to do it.

Would you be able to update the docs to include some more info on this?

**Comment by ItamarShDev** [comment]
Well, i'm not the maintainer  - but a user like you
you can look [here](https://github.com/whitequark/rainbowth/issues/12) for a similar issue

What you need to do is pretty simple:
1. open Sublime Text Packages folder (ctrl+shift+p -> `Browse Packages`)
2. Find your scheme inside `User` folder
3. If it is a compressed file - > uncompress it
4. Copy the `tmTheme` file to `Packages` folder under a new folder with the scheme name

Finally, select this scheme in sublime, and open a file to watch the magic :)

**Comment by ItamarShDev** [comment]
BTW I have been using Color Highlighter plugin and i realized it was conflicting with this plugin.

**Comment by EvilJordan** [comment]
@ItamarShDev Thanks for the instructions and help! What if, at step 2, there does not exist a scheme inside one's User folder?

**Comment by ItamarShDev** [comment]
@EvilJordan then it elsewhere

Though I just go to the scheme site (Usually Github page), and download the tmTheme to the appropriate location :)

**Comment by ghost** [comment]
I'm on Windows and also can't get it to work. The console says:
`FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\scott\\AppData\\Roaming\\Sublime Text 3\\Packages/Color Scheme - Default/Monokai.tmTheme'`

Monokai is one of the built-in schemes in ST. I get similar errors when I switch to any of the others.

**Comment by whitequark** [comment]
Please [read the README](https://github.com/whitequark/rainbowth#installation) and follow the instructions.

**Comment by EvilJordan** [comment]
@whitequark We have read the README. At least in my (and @scottmartin-code's) case, built-in themes do not seem to be available for unpacking, so the instructions are not relevant. Any advice?

**Comment by EvilJordan** [comment]
Found how to fix it (but I have not tried yet) from a previous commenter on the same issue in another closed thread: [https://github.com/whitequark/rainbowth/issues/12#issuecomment-198450897](https://github.com/whitequark/rainbowth/issues/12#issuecomment-198450897)

Hopefully, this will work, and it might be worth updating the README to include these steps to avoid this issue in the future.

**Comment by whitequark** [comment]
Ah OK, will do

**Comment by whitequark** [comment]
Updated README.

**Comment by ankushdharkar** [comment]
I have posted some detailed instructions for setup [here](https://github.com/ankushdharkar/rainbowth/blob/546b0603815ca2be93d9d809c09226b81768fd1a/Setup-Instructions.md)

PR #25 does the same

**Comment by eniac314** [comment]
Great! thank you, it works for me too now.
