### ISSUE TITLE
Update package control

### ISSUE THREAD

**Issue by Kamik423** [whitequark/rainbowth#34]
I have been debugging a lot of issues with rainbowth recently and found, that most of these were fixed as soon as I deleted the package control version and installed the GitHub version manually. (disable inside string, languages beginning with `text.`).

The package control version was most recently updated 3 years ago.
The GitHub version was most recently updated 1 year ago.

Can this newer version please be pushed out to package control, so people stop having these issues, that you already fixed?

**Comment by whitequark** [comment]
Done: https://github.com/whitequark/rainbowth/releases/tag/v2.3.0

**Comment by Kamik423** [comment]
Does a new GitHub release automatically propagate to package control? As of **now** it is not updated yet:

https://packagecontrol.io/packages/Rainbowth

**Comment by whitequark** [comment]
Well it should: https://packagecontrol.io/docs/submitting_a_package

**Comment by Kamik423** [comment]
Ok, just checked again and it is updated. Just in case anybody reading this thread is wondering.
