### ISSUE TITLE
Doesn't look quite right (ST3 Build 3083, OS X 10.10.4)

### ISSUE THREAD

**Issue by notduncansmith** [whitequark/rainbowth#7]
You can see in the image below, the brackets are highlighted, but not in the way I was expecting.

Was able to reproduce with multiple color schemes.

![image](https://cloud.githubusercontent.com/assets/4539683/8769744/f97687a4-2e58-11e5-9cdc-b749df3378bc.png)

**Comment by code-chimp** [comment]
Same issue with Build 3095 on Ubuntu 14.04LTS

**Comment by whitequark** [comment]
It appears that Sublime has changed the way regions are rendered. I worked around that using a bunch of gross, heinous hacks that involve caching, parsing XML with regexps, and synchronously executing stuff when selection changes. Nevertheless, this should be robust, and it seems pretty snappy on a random 500-line file I pulled from Clojure. Tell me if this causes any issues.

**Comment by notduncansmith** [comment]
Confirmed it's working for me:
<img width="161" alt="screenshot 2015-08-10 11 57 51" src="https://cloud.githubusercontent.com/assets/4539683/9180398/2263a138-3f57-11e5-8593-46089950a6ff.png">

Thanks for your hard work!

**Comment by maackle** [comment]
I'm still having issues even with latest master. I get two types of failure, depending on when I switch windows.

ST Build 3083

![image](https://cloud.githubusercontent.com/assets/896230/9377019/5b4564b8-46c9-11e5-854a-ca96f8134e6d.png)

![image](https://cloud.githubusercontent.com/assets/896230/9377050/98cb543c-46c9-11e5-80e5-f83572ac12ae.png)

Here's a console trace:

``` py
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 288, in on_selection_modified
    callback.on_selection_modified(v)
  File "/Users/michael/Library/Application Support/Sublime Text 3/Packages/rainbowth/rainbowth.py", line 225, in on_selection_modified
    view_info.update(old_highlighted_line, highlighted_line)
  File "/Users/michael/Library/Application Support/Sublime Text 3/Packages/rainbowth/rainbowth.py", line 39, in update
    visible_regions.remove(region)
ValueError: list.remove(x): x not in list
```

**Comment by whitequark** [comment]
OK, can you try https://github.com/whitequark/rainbowth/commit/b628f5e7d43aa0158a263be794450ab48af197b2 ?

**Comment by maackle** [comment]
That totally worked! This is the first time Rainbowth has actually worked for me. :clap: Thanks very much.

![image](https://cloud.githubusercontent.com/assets/896230/9402453/74878824-4792-11e5-8d20-df4a9ce67e6d.png)
